name: AnimationLib
version: 1.6.9
main: me.megamichiel.animationlib.bukkit.AnimLibPlugin
author: megamichiel
load: STARTUP
api-version: 1.13

commands:
  animationlib:
    usage: /<command> reload
    permission: animationlib.reload
    description: Plugin command
    aliases: animlib
